//首页
export const GET_HOME_SWIPE_DATA = "GET_HOME_SWIPE_DATA";
export const GET_HOME_LIST_DATA = "GET_HOME_LIST_DATA";

//详情


//订单


//注册&登录
export const PERSON_QUERY_BASE = 'PERSON_QUERY_BASE';
export const GET_PERSON_LOGIN_INFO = 'GET_PERSON_LOGIN_INFO';
export const CHANGE_PERSON_LOGIN_INFO = 'CHANGE_PERSON_LOGIN_INFO';